### PR TITLE
use the new sound pool API in the game

### PR DESCRIPTION
**Pull request by jason-simmons**

### CODE REVIEW

**Comment by eseidelGoogle** [comment]
This breaks iOS, correct? @chinmaygarde

**Comment by jason-simmons** [comment]
Actually, the change that breaks iOS is https://github.com/flutter/flutter/pull/845.  The SoundEffectPlayer in flutter_sprites is now using the SoundPool mojo interface, which isn't implemented on iOS.

To get this working on iOS, we could implement SoundPool for iOS or have SoundEffectPlayer continue to use MediaPlayer when running on iOS.

**Comment by eseidelGoogle** [comment]
lgtm

**Comment by vlidholt** [comment]
lgtm

**Pull request merged**
